### ISSUE TITLE
Iprob tételeknél a differenciát megkéne nézni

### ISSUE THREAD

**Issue by dRacz3** [dRacz3/ZV_Tetelek#2]
Megvan még valakinek a iprob 2 vizsgás kidolgozása? Nekem már nincs

**Comment by Fittah** [comment]
https://www.dropbox.com/sh/c8lpfy4q35j2b8l/AADxMylPf6bkCnsuv3-roMHBa?dl=0
14.tétel asszem ami kell. ott van hajrá
